name=SevenSegDisplays_ESP32
version=3.0.0
author=Gabriel D. Goldman <gdgoldman67@hotmail.com>
maintainer=Gabriel D. Goldman <gdgoldman67@hotmail.com>
sentence=7 segment 
paragraph=Provides a commong API
category=Display
url=https://github.com/GabyGold67/
depends=ShiftRegGPIOXpander_ESP32
architectures=esp32
