name=SevenSegDisplays_ESP32
version=3.2.1
author=Gabriel D. Goldman <gdgoldman67@hotmail.com>
maintainer=Gabriel D. Goldman <gdgoldman67@hotmail.com>
sentence=A Seven Segments Displays controller hardware agnostic API library providing several amenities and services. 
paragraph=Provides a common API to display data on 'Seven segments displays modules' with 'Seven segments display controllers' combinations, including different display digits quantities, common anode or common cathode leds wiring, dynamic or static refreshing needed, different 'Seven segment controller modules'. 
category=Display
url=https://github.com/GabyGold67/
includes=SevenSegDisplays.h, SevenSegHw.h
depends=ShiftRegGPIOXpander_ESP32
architectures=esp32
