/**
 * @file SevenSegDisplays.h
 * @brief Header file for the SevenSegDisplays_ESP32 library 
 * 
 * @details The library provides a common API and tools to generate and manage contents formatting for seven segments displays.
 * 
 * The library processes the information provided as input and displays the resulting data in a two stages process:
 * - A SevenSegDisplays class object manages the data generation from the user provided information into a hardware display valid input format.
 * - A SevenSegDispHw subclass object will manage the hardware required actions to exhibit the information generated by the SevenSegDisplays object.  
 * - For this mechanism to work the SevenSegDispHw subclass object will compose the SevenSegDisplays class object.  
 * The chosen design let's the information generated by the SevenSegDisplays class objects to be displayed in any kind of display architecture, as long as a SevenSegDispHw subclass implements the hardware communications protocols to receive the available processed data and to keep it exhibited and updated. 
 * 
 * @author Gabriel D. Goldman
 * 
 * @version 3.0.0
 * 
 * @date First release: 20/12/2023 
 *       Last update:   13/03/2025 13:40 (GMT+0200)
 * 
 * @copyright Copyright (c) 2025  GPL-3.0 license
 *******************************************************************************
  * @attention	This library was originally developed as part of the refactoring
  * process for an industrial machines security enforcement and productivity control
  * (hardware & firmware update). As such every class included complies **AT LEAST**
  * with the provision of the attributes and methods to make the hardware & firmware
  * replacement transparent to the controlled machines. Generic use attributes and
  * methods were added to extend the usability to other projects and application
  * environments, but no fitness nor completeness of those are given but for the
  * intended refactoring project, and for the author's projects requirements.  
  * 
  * @warning **Use of this library is under your own responsibility**
  * 
  * @warning The use of this library falls in the category described by The Alan 
  * Parsons Project (c) 1980 Games People play:   
  * Games people play, you take it or you leave it
  * Things that they say aren't alright
  * If I promised you the moon and the stars, would you believe it?
  * Games people play in the middle of the night
 *******************************************************************************
 */
//FFDR For Future Development Reminder comments!!
//FTPO For testing purposes only comments!!

#ifndef _SevenSegDisplays_H_
#define _SevenSegDisplays_H_

#include <Arduino.h>
#include <stdint.h>
#include <SevenSegDispHw.h>

const int MAX_DIGITS_PER_DISPLAY{8};

class SevenSegDisplays {
   static uint8_t _displaysCount;
   static uint16_t _dspLastSerialNum;
   static SevenSegDisplays** _ssdInstancesLstPtr;

   static TimerHandle_t _blinkTmrHndl;
   static TimerHandle_t _waitTmrHndl;

   static void tmrCbBlink(TimerHandle_t blinkTmrCbArg);
   static void tmrCbWait(TimerHandle_t waitTmrCbArg);

   static const unsigned long _minBlinkRate{100};
   static const unsigned long _maxBlinkRate{2000};

private:
   uint8_t _waitChar {0xBF};
   uint8_t _waitCount {0};
   bool _waiting {false};
   unsigned long _waitRate {250};
   unsigned long _waitTimer {0};

protected:
   bool* _blinkMaskPtr{nullptr};
   uint8_t* _dspAuxBuffPtr{nullptr};
   bool _dspBuffChng{false};
   uint8_t* _dspBuffPtr{nullptr};
   uint8_t _dspDigitsQty{};
   SevenSegDispHw* _dspUndrlHwPtr{};
   SevenSegDisplays* _dspInstance{nullptr};
   uint16_t _dspInstNbr{0};
   int32_t _dspValMax{};
   int32_t _dspValMin{};
    
   bool _blinking{false};
   bool _blinkShowOn{false};
   unsigned long _blinkTimer{0};
   unsigned long _blinkOffRate{500};
   unsigned long _blinkOnRate{500};
   unsigned long _blinkRatesGCD{500};  //Holds the value for the minimum timer checking the change ON/OFF of the blinking, saving unneeded timer interruptions, and without the need of the std::gcd function
   String _charSet{"0123456789AabCcdEeFGHhIiJLlnOoPqrStUuY-_=~* ."}; // for using indexOf() method
   uint8_t _charLeds[45] = {   //Values valid for a Common Anode display. For a Common Cathode display values must be logically bit negated
      0xC0, // 0
      0xF9, // 1
      0xA4, // 2
      0xB0, // 3
      0x99, // 4
      0x92, // 5
      0x82, // 6
      0xF8, // 7
      0x80, // 8
      0x90, // 9
      0x88, // A
      0xA0, // a
      0x83, // b
      0xC6, // C
      0xA7, // c
      0xA1, // d
      0x86, // E
      0x84, // e
      0x8E, // F
      0xC2, // G
      0x89, // H
      0x8B, // h
      0xF9, // I
      0xFB, // i
      0xF1, // J
      0xC7, // L
      0xCF, // l
      0xAB, // n
      0xC0, // O
      0xA3, // o
      0x8C, // P
      0x98, // q
      0xAF, // r
      0x92, // S
      0x87, // t
      0xC1, // U
      0xE3, // u
      0x91, // Y
      0xBF, // Minus -
      0xF7, // Underscore _
      0xB7, // Low =
      0xB6, //~ for Equivalent symbol
      0x9C, // °
      0xFF, // Space
      0x7F  //.
   };    
    
   uint8_t _space {0xFF};
   uint8_t _dot {0x7F};
   String _zeroPadding{""};
   String _spacePadding{""};

   unsigned long _blinkTmrGCD(unsigned long blnkOnTm, unsigned long blnkOffTm);
   void _popSsd(SevenSegDisplays** &ssdInstncObjLst, SevenSegDisplays* ssdToPop);
   void _pushSsd(SevenSegDisplays** &ssdInstncObjLst, SevenSegDisplays* ssdToPush);
   void _restoreDspBuff();
   void _setAttrbts();
   void _setDspBuffChng();
   void _saveDspBuff();
   void _updBlinkState();
   void _updWaitState();

public:
   /**
    * @brief Default constructor
    * 
    * @class SevenSegDisplays
    */
   SevenSegDisplays();
   /**
    * @brief Class constructor
    * 
    * Instantiates a SevenSegDisplays class object
    * 
    * @param dspUndrlHw A pointer to an instantiated SevenSegDispHw subclass object that models the hardware display that composes the SevenSegDisplays object
    */
   SevenSegDisplays(SevenSegDispHw* dspUndrlHwPtr);
    /**
     * @brief Class destructor
     */
    ~SevenSegDisplays();
   /**
    * @brief Makes the display blink the contents it is showing.
    * 
    * The display will blink the contents it is showing until a **`noBlink()`** method is invoked. The display will continue blinking even if the contents are changed.  
    * By default all the digits will be set to blink, but each digit might be configured individually to blink or not by using the **`setBlinkMask(const bool*)`** method.  
    * When invoking the **`blink()`** method with no parameters the blinking pace (timmings) previously set will be used. If no **`setBlinkRate(const unsigned long, const unsigned long)`** and no **`blink(const unsigned long, const unsigned long)`** with parameters was used before this call, the blinking will be symmetrical, meaning that the time the display shows the contents and the time the display is blank are equal. The on time and the off time of the blinking starts at a preset rate this first time the method is invoked.    
    * The blinking rate can be changed by using the **`setBlinkRate(const unsigned long, const unsigned long)`** method. After changing the blinking rate, the new blinking rate will be kept after a **`noBlink()`** call is done, until it is modified with a new **`setBlinkRate(const unsigned long, const unsigned long)`** call, or it is restarted by a **`blink(const unsigned long, const unsigned long)`** with parameters.  
    * @note To restart the blinking with a **`blink()`** or a **`blink(const unsigned long, const unsigned long)`** the service must first be stopped, as the method call makes no changes if the blinking service was already running.  
    * 
    * @retval true: If the display was not already set to blink (so now the blinking was started)
    * @retval false: The display was already set to blink
    */
   bool blink();
   /**
    * @brief Makes the display blink the contents it is showing.
    * 
    * Makes the display blink the contents it shows until a **`noBlink()`** method is invoked. The blinking is **symmetrical** if only one parameter is passed, **asymmetrical** if two **different** parameters are passed, meaning that the time the display shows the contents and the time the display is blank will be equal (symmetrical) or not (asymmetrical), depending of those two parameters. The blinking starts at a passed rate when the method is invoked. The blinking rate can be changed by using the **`.setBlinkRate(const unsigned long, const unsigned long)`** method. The blink rate set will be kept after a **`.noBlink()`**, until it is modified with a new **`.setBlinkRate(const unsigned long, const unsigned long)`** call, or it is restarted by a **`.blink(const unsigned long, const unsigned long)`** with parameters.  
    *   
    * @note To restart the blinking with a **`blink()`** or a **`blink(const unsigned long, const unsigned long)`** the service must first be stopped, as the method call makes no changes if the blinking service was already running.  

   * @param onRate Value indicating the time (in milliseconds) the display must stay on, the value must be in the range _minBlinkRate <= onRate <= _maxBlinkRate. Those preset values can be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods.
   * @param offRate Optional value indicating the time (in milliseconds) the display must stay off, the value must be in the range _minBlinkRate <= offRate <= _maxBlinkRate. Those preset values might be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods. If no offRate value is provided the method will assume it's a symmetric blink call and use a value for offRate equal to the value passed for onRate. 
   * 
   * @retval true If the display was not already set to blink (so now the blinking was started).  
   * @retval false The display was already set to blink, and/or one or more of the parameters passed were out of range.  
   */
   bool blink(const unsigned long &onRate, const unsigned long &offRate = 0);
   /**
    * @brief Clears the display, turning off all the segments and dots.
    * 
    * To ensure success the method must also clean auxiliary buffers used to save the main buffer contents while blinking, as the backup buffer will be restored, so the display clear() would be reverted  
    * 
    * @note The method will not produce any change if it's in "Waiting mode" as the blanked ports will be immediately overwritten by the waiting process, so it makes no sense. Consider, though, that the "Waiting mode" clears the display at it's exit.  
    */
   void clear();
   /**
    * @brief Displays a basic graphical representation of the level of fulfillment or completeness of two segmented values or tasks
    * 
    * The data displayed gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top), and a character might be added before each of the graphical representations to give an indication of what the display is showing, passed through the **labelLeft** and **labelRight** parameters. As four 7 segments digit ports will be used, this method only applies to displays with 4 to 8 LED digits, the display is splitted in two sectors, the left side and the right side, and each one of them must have a valid value (0 <= value <= 3) to enable them to be displayed, and might have (or not) a single displayable character to give a visual hint to what the value is showing. For more information check the **`gauge(const int, char)`** method.
    * 
    * @param levelLeft The integer value to display must be in the range 0 <= level <= 3 for the two leftside 7 segments displays.  
    * @param levelRight The integer value to display must be in the range 0 <= level <= 3 for the two rightside 7 segments displays.  
    * @param labelLeft A char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`print()`** method description.  
    * @param labelRight A char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the position left to the **levelRight** display, just before the levelRight value. The character must be one of the "displayable" characters, as listed in the **`.print(String)`** method description.
    * 
    * @retval true: If the values could be represented.  
    * @retval false: Otherwise, being that the **levelLeft** and/or **levelRight** parameter was out of range and/or the **labelLeft** and/or **labelRight** parameter was not in the list of displayable characters. The display will be blanked. 
    */
   bool doubleGauge(const int &levelLeft, const int &levelRight, char labelLeft = ' ', char labelRight = ' ');
   /**
    * @brief Displays a basic graphical representation of the level of fulfillment or completeness of a segmented value or task.
    * 
    * The displayed data gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top, and from left to right), and a character might be added before the graphical representation to give an indication of what the display is showing, passed through the **label** parameter. This method is usable in displays which have from 4 and up to 8 digits, and the representation always makes use of exactly 4 digits. 
    * 
    * @param level The integer value to display must be in the range 0 <= level <= 3.  
    * @param label char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`print(String)`** method description.
    * 
    * @return true If the value could be represented.  
    * @return false Otherwise, being that the **level** parameter was out of range and/or the **label** parameter was not in the list of displayable characters. The display will be blanked.
    */
   bool gauge(const int &level, char label = ' ');
   /**
    * @brief Displays a basic graphical representation of the level of fulfillment or completeness of a segmented value or task
    * 
    * The data displayed gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top, and from left to right), and a character might be added before the graphical representation to give an indication of what the display is showing, passed through the **label** parameter. 
    * 
    * @param level The double value to display must be in the range 0.0 <= level <= 1.0, being the range the representation of the percentage of the 'full' level, so that the ranges are:  
    * 0.0 <= level < 0.25 for the first level,  
    * 0.25 <= level < 0.50 for the second level,  
    * 0.50 <= level < 0.75 for the third level, and  
    * 0.75 <= level <= 1.00 for the fourth and upper level.  
    * 
    * @param label char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`print(String)`** method description.  
    *
    * @return true If the value could be represented.  
    * @return false Otherwise, being that the **level** parameter was out of range and/or the **label** parameter was not in the list of displayable characters. The display will be blanked.  
    */
   bool gauge(const double &level, char label = ' ');
   /**
    * @brief Return the number of digits of the display hardware.  
    * 
    * Returns an unsigned short integer value indicating the the quantity of digits (ports), the display have as declared at the object instantiation. Each time the class is instantiated the object is created with the needed resources and the range of values it's capable of displaying are calculated based on the dspDigits parameter, and that value is the one returned by this method.  
    * 
    * @return The unsigned short number indicating the quantity of digits of the instantiated display.
    */
   uint8_t getDigitsQty();
   /**
    * @brief Returns a value equivalent to the greatest displayable number for the display.  
    * 
    * The value indicates the greatest displayable number according to the quantity of digits (ports) the display have as indicated at the object instantiation.  
    * 
    * @return The integer number indicating the maximum value that the display might display according to the quantity of digits of the instantiated display.  
    */
   int32_t getDspValMax();
   /**
    * @brief Returns a value equivalent to the smallest displayable number for the display. 
    * 
    * The value indicates the smallest displayable number according to the quantity of digits (ports) the display have as indicated at the object instantiation.
    * 
    * @return The integer number indicating the minimum value that the display might display according to the quantity of digits of the instantiated display.  
    */
   int32_t getDspValMin();
   /**
    * @brief Returns a unique numeric identification of the object
    * 
    * The Returned unsigned integer value identifies the object. Each time the class is instantiated the created object receives a serial instantiation number that can be used in order to identify each object in case of need.
    * 
    * @return The unsigned number indicating the identification Instance Number. 
    * 
    * @note As SevenSegDisplays objects might be constructed and destructed at need, the largest Instance number is not necesarily coincidental with the quantity of objects instantiated at any given moment, as the numeric identification of the object is an always increasing value incremented every time a new object is instantiated, but never decremented due to destructions.  
    * 
    * @attention Not to be confused with a pointer to the object or other internal unique identification mechanism results
    */
   uint16_t getInstanceNbr();
   /**
    * @brief Returns the maximum rate the display can be configured to blink at. 
    * 
    * The maximum rate the display can be configured to blink at helps keeping the blinkRate setters inside the accepted range. At least two aspects of the blinking process are involved in the determination if this value.  
    * - The technical aspect is related to the hardware possibility to manage the display contents change to show the blinking effect. 
    * - The perception aspect is related to keep the blinking effect range in a rhythm at which the display turns on and off as part of the information that it provides, and doesn't make it look like a display failure or any other kind of bug.  
    * 
    * @return The maximum time, in milliseconds, the display can be set to blink. This value is the maximum to set as the turned-on or the turned-off stage of the blinking process started by a **`blink()`** or a **`blink(const unsigned long, const unsigned long)`** method.  
    * 
    * @attention Opposite to the concept of Hertz, that designates how many times an action happens in a fixed period of time (a second), the value used in the `blink()` and all related methods is **the time set to elapse before the next action happens**.  
    */
   unsigned long getMaxBlinkRate();
   /**
    * @brief Returns the minimum rate the display can be configured to blink at. 
    * 
    * The minimum rate the display can be configured to blink at helps keeping the blinkRate setters inside the accepted range. At least two aspects of the blinking process are involved in the determination if this value.  
    * - The technical aspect is related to the hardware possibility to manage the display contents change to show the blinking effect. 
    * - The perception aspect is related to keep the blinking effect range in a rhythm at which the display turns on and off as part of the information that it provides, and doesn't make it look like a display failure or any other kind of bug.  
    * 
    * @return The minimum time, in milliseconds, the display can be set to blink. This value is the minimum to set as the turned-on or the turned-off stage of the blinking process started by a **`.blink()`** or a **`blink(const unsigned long, const unsigned long)`** method.  
    * 
    * @attention Opposite to the concept of Hertz, that designates how many times an action happens in a fixed period of time (a second), the value used in the `blink()` and all related methods is **the time set to elapse before the next action happens**.  
    */
   unsigned long getMinBlinkRate();
   /**
    * @brief Returns a value indicating if the display is blank. 
    * 
    * The condition of blank is the one in which "All the display ports/digits of the display show spaces, and no decimal points or semicolons are active". This definition is important as it not refers to the display buffer holding any specific arbitrary value (0x00 or 0xFF) but the value designated as **_space**.  
    * 
    * @retval true The display buffer is filled with _space values
    * @retval false At least one memory element of the buffer is filled with a value that is not a _space
    */
   bool isBlank();
   /**
    * @brief Returns a boolean value indicating if the display is set to blink or not.
    * 
    * @retval true The display is set to blink.  
    * @retval false The display is set not to blink.   
    */
   bool isBlinking();
   /**
    * @brief Returns a boolean value indicating if the display is set to "waiting mode" or not.
    * 
    * Knowing if the display is set to "waiting mode" might be useful as the display will force the mode disabling if a **`print()`**, **`write()`**, **`gauge()`**, etc. methods is invoked.
    * 
    * @return true If the display is set to **Waiting mode**.  
    * @return false If the display is not set to **Waiting mode**.   
    */
   bool isWaiting();
   /**
    * @brief Stops the display blinking, if it was doing so, leaving the display turned on.
    * 
    * Stoping the blinking process includes retrieving the original contents from the _dspAuxPtr pointed memory (the Auxiliar Buffer), freeing the Auxiliar Buffer memory, stoping the timer attached to the process and cleaning the blinking state related flags  
    * 
    * @retval true If the display was set to blink, the blinking is stopped.  
    * @retval false If the display was not set to blink, no changes will be done.  
    */
   bool noBlink();
   /**
    * @brief Stops the **Waiting mode**, if it was doing so, leaving the display turned on. 
    * 
    * Stoping the "Waiting mode" process includes retrieving the original contents from the _dspAuxPtr pointed memory (the Auxiliar Buffer), freeing the Auxiliar Buffer memory, stoping the timer attached to the process and cleaning the waiting state related flags    
    * 
    * @retval true If the display was set to wait, the **Waiting mode** is stopped.  
    * @retval false If the display was not set to wait, no changes will be done.  
    */
   bool noWait();
   /**
    * @brief Displays a text string.
    * 
    * The text string must contains all "displayable" characters, which are the ones included in the following list: **0123456789AabCcdEeFGHhIiJLlnOoPqrStUuY-_.** and the **space**. There are other special characters displayable, details in the notes.  
    * 
    * @param text String, up to **dspDigits** displayable characters long PLUS usable dots, all characters included in the representable characters list. Each valid character might be followed by a "." if needed, without being counted as a character, even spaces and special chars. If two or more consecutive dots are passed, an intermediate space is considered to be included between each pair of them, and that space counts as one of the available characters to display.  
    * 
    * @retval true If the text complies with the requirements to be represented. The text string will be displayed.   
    * @retval false Otherwise. The display will be blanked.  
    * 
    * @note There are other 3 characters that can be represented in the display, but the conversion from a character to use while programming is "host language setting dependant", so those where assigned to available ASCII non displayable characters of easy access in any keyboard layout in most languages, they can be used as part of the text string to display, and they are:  
    * **=** Builds a character formed by lighting the lower 2 horizontal segments (the d and g segments) of the digit display, can be described as a "lower equal" symbol.    
    * **~** Builds a character formed by lighting the 3 horizontal segments (the a, d and g segments) of the digit display, can be described as an "equivalent" symbol.  
    * **'*'** (asterisk) Builds a character by lighting the upper 4 segments (the a, b, f and g segments), forming a little square, can be described as the "degrees" symbol or º. 
    */
   bool print(String text);
   /**
    * @brief Displays an integer value as long as the length representation fits the available space of the display.  
    * 
    * @param value The integer value to display which must be in the range (-1)*(pow(10, (dspDigits - 1)) - 1) <= value <= (pow(10, dspDigits) - 1), or _dspValMin <= value <= _dspValMax.  
    * @param rgtAlgn Boolean, optional parameter (if not specified the default value, false, will be assumed), indicates if the represented value must be displayed right aligned, with the missing heading characters being completed with spaces or zeros, depending in the **zeroPad** optional parameter. When a negative value is displayed and it's less than (dspDigits - 1) digits long, a right aligned display will keep the '-' sign in the leftmost position, and the free space to the leftmost digit will be filled with spaces or zeros, depending in the **zeroPad** optional parameter.  
    * @param zeroPad Boolean, optional parameter (if not specified the default value, false, will be assumed), indicates if the heading free spaces of the integer right aligned displayed must be filled with zeros (true) or spaces (false). In the case of a negative integer the spaces or zeros will fill the gap between the '-' sign kept in the leftmost position, and the first digit.  
    * @return true If the value could be represented.  
    * @return false If the value couldn't be represented as it was out of the valid range. The display will be blanked.  
    */
   bool print(const int32_t &value, bool rgtAlgn = false, bool zeroPad = false);
   /**
    * @brief Displays a floating point value.  
    * 
    * The floating point value will be displayed as long as the length representation fits the available space of the display. If the integer part of value is not in the displayable range or if the sum of the spaces needed by the integer part plus the indicated decimal places to display is greater than the available digits space, the **`print()`** will fail, returning a false value and clearing the display.
    * 
    * @param value The floating point value which must be in the range ((-1)*(pow(10, ((dspDigits - decPlaces) - 1)) - 1)) <= value <= (pow(10, (dspDigits - decPlaces)) - 1), or _dspValMin <= value <= _dspValMax.  
    * @param decPlaces Decimal places to be displayed after the decimal point, ranging 0 <= decPlaces < dspDigits, selecting 0 value will display the number as an integer, with no '.' displayed. In any case the only modification that will be applied if value has a decimal part longer than the decPlaces number of digits is **truncation**, if any other rounding criteria is desired the developer must apply it to **value** before calling this method.  
    * @param rgtAlgn Boolean, optional parameter (if not specified the default value, false, will be assumed), indicates if the represented value must be displayed right aligned, with the missing heading characters being completed with spaces or zeros, depending in the zeroPad optional parameter. When a negative value is displayed and it's less than (dspDigits - 1) digits long, a right aligned display will keep the '-' sign in the leftmost position, and the free space to the leftmost digit will be filled with spaces or zeros, depending in the zeroPad optional parameter.  
    * @param zeroPad Boolean, optional parameter (if not specified the default value, false, will be assumed), indicates if the heading free spaces of the value right aligned displayed must be filled with zeros (true) or spaces (false). In the case of a negative value the spaces or zeros will fill the gap between the '-' sign kept in the leftmost position, and the first digit.  
    * 
    * @retval true The value could be represented.  
    * @retval false The value couldn't be represented. The display is blanked.  
    */
   bool print(const double &value, const unsigned int &decPlaces, bool rgtAlgn = false, bool zeroPad = false);
   /**
    * @brief Resets the blinking mask.  
    * 
    * The blinking mask configures which digits of the display will be affected by the **`.blink()`** method. This method resets the mask so that **all** the digits will be affected when blinking is active.  
    */
   void resetBlinkMask();
   /**
    * @brief Sets a new **blinking mask** for the display.  
    * 
    * The blinking mask indicates which digits will be involved when a **`blink()`** method is invoked. Indicating true for a digit makes it blink when the method is called, indicating false makes it display steady independently of the other digits. The parameter is positional referenced to the display, and for ease of use the index numbers of the array indicate their position relative to the rightmost digit (blnkPort0). The mask might be reset to its original value (all digits set to blink) by using this method with all parameters set to **true** or by using the **`resetBlinkMask()`** method.  
    * 
    * @param newBlnkMsk Array of booleans of length **dspDigits**, indexes are positional referenced to the display, indicating each one which digits must blink after a **`blink()`** method is invoked (true) or stay steady (false). The indexes valid range is 0 <= index <= (dspDigits-1), corresponding the [0] position withe the rightmost display port, the [1] position the second from the right and so on.  
    */
   void setBlinkMask(const bool* newBlnkMsk);
   /**
    * @brief Changes the time parameters to use for the display blinking of the contents it shows.  
    * 
    * The parameters change will take immediate effect, either if the display is already blinking or not, in the latter case the parameters will be the ones used when a **`blink()`** method is called without parameters. The blinking will be **symmetrical** if only one parameter is passed, **asymmetrical** if two different parameters are passed, meaning that the time the display shows the contents and the time the display is blank will be equal (symmetrical) or not equal (asymmetrical), depending of those two parameters. The blink rate set will be kept after a **`noBlink()`** or new **`blink()`** without parameters call is done, until it is modified with a new **`setBlinkRate()`** call, or it is restarted by a **`blink()`** with parameters. Note that to restart the blinking with a **`blink()`** the service must first be stopped, as the method makes no changes if the blinking service was already running.  
    * 
    * @param newOnRate unsigned long integer containing the time (in milliseconds) the display must stay on, the value must be in the range _minBlinkRate <= onRate <= _maxBlinkRate. Those built-in values can be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods.  
    * @param newOffRate optional unsigned long integer containing the time (in milliseconds) the display must stay off, the value must be in the range _minBlinkRate <= offRate <= _maxBlinkRate. Those built-in values can be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods. If no offRate value is provided the method will assume it's a symmetric blink call and use a value of offRate equal to the value passed by onRate.  
    * 
    * @return true The parameter or parameters passed are within the valid range, The change will take effect immediately.  
    * @return false One or more of the parameters passed were out of range. The rate change would not be made for none of the parameters.  
    */
   bool setBlinkRate(const unsigned long &newOnRate, const unsigned long &newOffRate = 0);
   /**
    * @brief Sets the "Waiting" character.  
    * 
    * The character used by the display to show the "process ongoing" a.k.a. "Waiting mode" can be changed. The default character set is the "-" (minus sign). The parameters change will take immediate effect, either if the display is already in wait mode or not. The new character will be changed for further calls of the method until a new setWaitChar is invoked with a valid argument, that means a "displayable character".  
    * 
    * @param newChar A character the display must use for symbolizing the progress, the value must be in the displayable characters group as explained in the print() method.  
    * @return true The character passed is within the displayable characters range, the change will take effect immediately.  
    * @return false The parameter passed was invalid, i.e. it was a non displayable character, the character change will not be made.  
    */
   bool setWaitChar (const char &newChar);
   /**
    * @brief Changes the timing parameter used to show the "progress ongoing bar advancement" speed.  
    * 
    * The parameter change will take immediate effect, either if the display is already in wait mode or not, in the latter case the parameter will be the one used when a **`wait()`** method is called without parameters. The wait rate set will be kept after a **`noWait()`** or new **`wait()`** without parameters call is done, until it is modified with a new **`setWaitRate()`** call, or it is restarted by a **`wait()`** with parameters. Note that to restart the waiting with a **`wait()`** the service must first be stopped, as the method makes no changes if the waiting service was already running.  
    * 
    * @param newWaitRate unsigned long integer containing the time (in milliseconds) the display must take to advance the next character symbolizing the progress, the value must be in the range _minBlinkRate <= newWaitRate <= _maxBlinkRate. Those values can be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods.  
    * 
    * @retval true The parameter passed is within the valid range, the change takes effect.
    * @retval false The parameter passed was out of range, the rate change will not be made.   
    */
   bool setWaitRate(const unsigned long &newWaitRate);
   /**
    * @brief Makes the display enter the "Waiting mode"  
    * 
    * While in "Waiting mode" the display shows a simple animated progress bar or "process ongoing bar" until a **`noWait()`** method is invoked. The speed rate for the progress animation starts at a parameter passed rate when the method is invoked, or the last speed set will be used, having a preset value for the first time it's invoked if no parameter is passed. The animation rate can be changed by using the **`setWaitRate()`** method. The speed rate set will be kept after a **`noWait()`** or new **`wait()`** without parameters call is done, until it is modified with a new **`setWaitRate()`** call, or it is restarted by a **`wait()`** with a parameter. Note that to restart the waiting with a **`wait()`** the service must first be stopped, as the method makes no changes if the waiting service was already running.  
    * 
    * @return true The display was not already set to wait (so now the "Waiting state" was started).  
    * @return false The display was already set to wait, and/or the parameter passed was out of range.  
    */
   bool wait();
   /**
    * @brief Makes the display enter the "Waiting mode" with a specific wait rate 
    * 
    * The method is similar to the **`wait()`** method, the only difference is that before entering the "Waiting state" a **`setWaitRate()`** is executed, using the provided argument to set the new wait rate.  
    * 
    * @param newWaitRate A new rate for the animated progress bar or "process ongoing bar".  
    * 
    * @return true The display was not already set to wait (so now the "Waiting state" was started).  
    * @return false The display was already set to wait, and/or the parameter passed was out of range.  
    */
   bool wait(const unsigned long &newWaitRate);
   /**
    * @brief Prints one character to the display, at a designated position (digit or port), without affecting the rest of the characters displayed.
    * 
    * @param segments An unsigned short integer value representing which segments to turn on and which off to get the graphic representation of a character in the seven segment display, the corresponding value can be looked up in the **_charLeds[]** array definition in the header file of the library. In the case of a common cathode display the values there listed must be complemented. Any other uint8_t (char or unsigned short int is the same here) value is admissible, but the displayed result might not be easily recognized as a known ASCII character.  
    * @param port unsigned short integer value representing the position or digit where the character will be sent, being the range of valid values 0 <= port <= (dspDigits - 1), the 0 value is the rightmost digit, the 1 value the second from the right and so on.
    * 
    * @retval true The parameters are within the acceptable range, in this case 0 <= port <= (dspDigits - 1).  
    * @retval false: The port value was outside the acceptable range.  
    */
   bool write(const uint8_t &segments, const uint8_t &port);
   /**
    * @brief Prints one character to the display, at a designated position (digit or port), without affecting the rest of the characters displayed.
    * 
    * @param character A single character string that must be displayable, as defined in the **`print()`** method.  
    * @param port unsigned short integer value representing the position or digit where the character will be sent, being the range of valid values 0 <= port <= (dspDigits - 1), the 0 value is the rightmost digit, the 1 value the second from the right and so on.
    * 
    * @retval true **character** is a displayable one char string, and **port** value is in the range 0 <= value <= (dspDigits - 1).  
    * @retval false **character** was not "displayable" or the **port** value was out of range.   
    */
   bool write(const String &character, const uint8_t &port);
};

#endif  //_SevenSegDisplays_H_