/**
 * @file SevenSegDisplays.h
 * @brief Header file for the SevenSegDisplays_ESP32 library 
 * 
 * @details The library provides a common API and tools to manage the contents formatting for seven segment segments displays.
 * 
 * The library processes the information provided as input and displays the information in a two stages process:
 * - A SevenSegDisplays class object manages the data generation from the uses provided information into a hardware display valid input format.
 * - A SevenSegDispHw subclass object will manage the hardware required actions to exhibit the information generated by the SevenSegDisplays object.  
 * - For this mechanism to work the SevenSegDispHw subclass object will compose the SevenSegDisplays class object.  
 * The chosen design let's the information generated by the SevenSegDisplays class objects to be displayed in any kind of architecture for the display, as long as a SevenSegDispHw subclass implements the hardware communications protocols to receive the available processed data. 
 * 
 * @author Gabriel D. Goldman
 * 
 * @version 3.0.0
 * 
 * @date First release: 20/12/2023 
 *       Last update:   11/03/2025 15:00 (GMT+0200)
 * 
 * @copyright Copyright (c) 2025  GPL-3.0 license
 *******************************************************************************
  * @attention	This library was developed as part of the refactoring process for
  * an industrial machines security enforcement and productivity control
  * (hardware & firmware update). As such every class included complies **AT LEAST**
  * with the provision of the attributes and methods to make the hardware & firmware
  * replacement transparent to the controlled machines. Generic use attributes and
  * methods were added to extend the usability to other projects and application
  * environments, but no fitness nor completeness of those are given but for the
  * intended refactoring project.
  * 
  * @warning **Use of this library is under your own responsibility**
  * 
  * @warning The use of this library falls in the category described by The Alan 
  * Parsons Project (c) 1980 Games People play:
  * Games people play, you take it or you leave it
  * Things that they say aren't alright
  * If I promised you the moon and the stars, would you believe it?
  * Games people play in the middle of the night
 *******************************************************************************
 */

#ifndef _SevenSegDisplays_H_
#define _SevenSegDisplays_H_

#include <Arduino.h>
#include <stdint.h>
#include <SevenSegDispHw.h>

const int MAX_DIGITS_PER_DISPLAY{8};
// const int MAX_DISPLAYS_QTY{10};  //FFDR The lenght of the array containing the pointers to the displays will become dynamic, use Push & pop from the ButtonToSwitch_AVR

class SevenSegDisplays {
   static uint8_t _displaysCount;
   static uint16_t _dspSerialNum;
   static uint8_t _dspPtrArrLngth;
   static SevenSegDisplays** _instancesLstPtr;

   static TimerHandle_t _blinkTmrHndl;
   static TimerHandle_t _waitTmrHndl;

   static void tmrCbBlink(TimerHandle_t blinkTmrCbArg);
   static void tmrCbWait(TimerHandle_t waitTmrCbArg);

   static const unsigned long _minBlinkRate{100};
   static const unsigned long _maxBlinkRate{2000};

   private:
   uint8_t _waitChar {0xBF};
   uint8_t _waitCount {0};
   bool _waiting {false};
   unsigned long _waitRate {250};
   unsigned long _waitTimer {0};

protected:
   bool* _blinkMaskPtr{nullptr};
   uint8_t* _dspAuxBuffPtr{nullptr};
   bool _dspBuffChng{false};
   uint8_t* _dspBuffPtr{nullptr};
   uint8_t _dspDigitsQty{};
   SevenSegDispHw _dspUndrlHw{};
   SevenSegDisplays* _dspInstance;
   uint16_t _dspInstNbr{0};
   int32_t _dspValMax{};
   int32_t _dspValMin{};
    
    bool _blinking{false};
    bool _blinkShowOn{false};
    unsigned long _blinkTimer{0};
    unsigned long _blinkOffRate{500};
    unsigned long _blinkOnRate{500};
    unsigned long _blinkRatesGCD{500};  //Holds the value for the minimum timer checking the change ON/OFF of the blinking, saving unneeded timer interruptions, and without the need of the std::gcd function
    String _charSet{"0123456789AabCcdEeFGHhIiJLlnOoPqrStUuY-_=~* ."}; // for using indexOf() method
    uint8_t _charLeds[45] = {   //Values valid for a Common Anode display. For a Common Cathode display values must be logically bit negated
        0xC0, // 0
        0xF9, // 1
        0xA4, // 2
        0xB0, // 3
        0x99, // 4
        0x92, // 5
        0x82, // 6
        0xF8, // 7
        0x80, // 8
        0x90, // 9
        0x88, // A
        0xA0, // a
        0x83, // b
        0xC6, // C
        0xA7, // c
        0xA1, // d
        0x86, // E
        0x84, // e
        0x8E, // F
        0xC2, // G
        0x89, // H
        0x8B, // h
        0xF9, // I
        0xFB, // i
        0xF1, // J
        0xC7, // L
        0xCF, // l
        0xAB, // n
        0xC0, // O
        0xA3, // o
        0x8C, // P
        0x98, // q
        0xAF, // r
        0x92, // S
        0x87, // t
        0xC1, // U
        0xE3, // u
        0x91, // Y
        0xBF, // Minus -
        0xF7, // Underscore _
        0xB7, // Low =
        0xB6, //~ for Equivalent symbol
        0x9C, // °
        0xFF, // Space
        0x7F  //.
    };    
    
    uint8_t _space {0xFF};
    uint8_t _dot {0x7F};
    String _zeroPadding{""};
    String _spacePadding{""};

    unsigned long _blinkTmrGCD(unsigned long blnkOnTm, unsigned long blnkOffTm);
    void _restoreDspBuff();
    void _saveDspBuff();
    void _setAttrbts();
    void _updBlinkState();
    void _updWaitState();

public:
/**
 * @brief Default constructor
 * 
 * @class SevenSegDisplays
 */
    SevenSegDisplays();
    /**
     * @brief Class constructor
     * 
     * Instantiates a SevenSegDisplays class object
     * 
     * @param dspUndrlHw An instantiated object of subclass SevenSegDispHw that models the hardwar displays that composes the SevenSegDisplays object
     */
    SevenSegDisplays(SevenSegDispHw dspUndrlHw);
    /**
     * @brief Default destructor
     */
    ~SevenSegDisplays();
    /**
     * @brief Makes the display blink the contents it is showing.
     * 
     * The display will blink the contents it is showing until a **`noBlink()`** method is invoked. The display will continue blinking even if the contents are changed. By default all the digits blink, but each digit might be configured individually to blink or not by using the **`void setBlinkMask(const bool*)`** method. When invoking the **`.blink()`** method with no parameters the blinking is symmetrical, meaning that the time the display shows the contents and the time the display is blank are equal. The blinking starts at a preset rate the first time the method is invoked. The blinking rate can be changed by using the **`bool setBlinkRate(const unsigned long, const unsigned long)`** method. After changing the blinking rate, the new blinking rate will be kept after a **`bool noBlink()`** or new **`bool blink()`** without parameters call is done, until it is modified with a new **`bool setBlinkRate(const unsigned long, const unsigned long)`** call, or it is restarted by a **`bool blink(const unsigned long, const unsigned long)`** with parameters. Note that to restart the blinking with a **`bool blink()`** the service must first be stopped, as the method call makes no changes if the blinking service was already running.  
     * 
     * @retval true: If the display was not already set to blink (so now the blinking was started)
     * @retval false: The display was already set to blink
     */
    bool blink();
    /**
     * @brief Makes the display blink the contents it is showing.
     * 
     * Makes the display blink the contents it shows until a **`noBlink()`** method is invoked. The blinking is **symmetrical** if only one parameter is passed, **asymmetrical** if two **different** parameters are passed, meaning that the time the display shows the contents and the time the display is blank will be equal (symmetrical) or not (asymmetrical), depending of those two parameters. The blinking starts at a passed rate when the method is invoked. The blinking rate can be changed by using the **`.setBlinkRate()`** method. The blink rate set will be kept after a **`.noBlink()`** or new **`.blink()`** without parameters call is done, until it is modified with a new **`.setBlinkRate()`** call, or it is restarted by a **`.blink()`** with parameters. Note that to restart the blinking with a **`.blink()`** the service must first be stopped, as the method makes no changes if the blinking service was already running.  
     * 
     * @param onRate Value indicating the time (in milliseconds) the display must stay on, the value must be in the range _minBlinkRate <= onRate <= _maxBlinkRate. Those preset values can be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods.
     * @param offRate Optional value indicating the time (in milliseconds) the display must stay off, the value must be in the range _minBlinkRate <= offRate <= _maxBlinkRate. Those preset values might be known by the use of the **`getMinBlinkRate()`** and the **`getMaxBlinkRate()`** methods. If no offRate value is provided the method will assume it's a symmetric blink call and use a value for offRate equal to the value passed for onRate. 
     * @retval true If the display was not already set to blink (so now the blinking was started).  
     * @retval false The display was already set to blink, and/or one or more of the parameters passed were out of range.  
     */
    bool blink(const unsigned long &onRate, const unsigned long &offRate = 0);
    /**
     * @brief Clears the display, turning off all the segments and dots.
     */
    void clear();
    /**
     * @brief Displays a basic graphical representation of the level of fulfillment or completeness of two segmented values or tasks
     * 
     * The data displayed gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top), and a character might be added before each of the graphical representations to give an indication of what the display is showing, passed through the **labelLeft** and **labelRight** parameters. As four 7 segments digit ports wiil be used, this method only applies to displays with 4 to 8 LED digits, the display is splitted in two sectors, the left side and the right side, and each one of them must have a valid value (0 <= value <= 3) to enable them to be displayed, and might have (or not) a single displayable character to give a visual hint to what the value is showing. For more information check the **gauge()** method.
     * 
     * @param levelLeft The integer value to display must be in the range 0 <= level <= 3 for the two leftside 7 segments displays.  
     * @param levelRight The integer value to display must be in the range 0 <= level <= 3 for the two rightside 7 segments displays.  
     * @param labelLeft A char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`.print()`** method description.  
     * @param labelRight A char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the position left to the **levelRight** display, just before the levelRight value. The character must be one of the "displayable" characters, as listed in the **`.print()`** method description.
     * 
     * @retval true: If the values could be represented.  
     * @retval false: Otherwise, being that the **levelLeft** and/or **levelRight** parameter was out of range and/or the **labelLeft** and/or **labelRight** parameter was not in the list of displayable characters, and the display will be blanked. 
     */
    bool doubleGauge(const int &levelLeft, const int &levelRight, char labelLeft = ' ', char labelRight = ' ');
    /**
     * @brief Displays a basic graphical representation of the level of fulfillment or completeness of a segmented value or task.
     * 
     * The displayed data gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top, and from left to right), and a character might be added before the graphical representation to give an indication of what the display is showing, passed through the **label** parameter. This method is usable in displays which have from 4 and up to 8 digits, and the representation always makes use of exactly 4 digits. 
     * 
     * @param level The integer value to display must be in the range 0 <= level <= 3.  
     * @param label char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`.print()`** method description.
     * 
     * @return true If the value could be represented.  
     * @return false Otherwise, being that the **level** parameter was out of range and/or the **label** parameter was not in the list of displayable characters, and the display will be blanked.
     */
    bool gauge(const int &level, char label = ' ');
    /**
     * @brief Displays a basic graphical representation of the level of fulfillment or completeness of a segmented value or task
     * 
     * The data displayed gives a general fast notion on the matter, as a battery charge level, liquids deposit level, time remaining, tasks completeness and so on. The levels are represented by the horizontal segments (0, 1, 2 or 3 from bottom to top, and from left to right), and a character might be added before the graphical representation to give an indication of what the display is showing, passed through the **label** parameter. 
     * 
     * @param level The double value to display must be in the range 0.0 <= level <= 1.0, being the range the representation of the percentage of the 'full' level, so that the ranges are:  
0.0 <= level < 0.25 for the first level,  
0.25 <= level < 0.50 for the second level,  
0.50 <= level < 0.75 for the third level, and  
0.75 <= level <= 1.00 for the fourth and upper level.  
     * @param label char, optional parameter (if not specified the default value, a Space, will be assumed), that will be displayed in the leftmost digit of the display. The character must be one of the "displayable" characters, as listed in the **`.print()`** method description.  
     *
     * @return true If the value could be represented.  
     * @return false Otherwise, being that the **level** parameter was out of range and/or the **label** parameter was not in the list of displayable characters, and the display will be blanked.  
     */
    bool gauge(const double &level, char label = ' ');
    /**
     * @brief Return the number of digits of the display hardware.  
     * 
     * Returns an unsigned short integer value indicating the the quantity of digits, or ports, the display have as declared at the object instantiation. Each time the class is instantiated the object is created with the needed resources and the range of values are calculated based on the dspDigits parameter, and that value is the one returned by this method.  
     * 
     * @return The unsigned short number indicating the quantity of digits of the instantiated display.
     */
    uint8_t getDigitsQty();
    /**
     * @brief Returns a value equivalent to the greatest displayable number for the display.  
     * 
     * The value indicates the greatest displayable number according to the quantity of digits, or ports, the display have as indicated at the object instantiation.  
     * 
     * @return The integer number indicating the maximum value that the display might display acording to the quantity of digits of the instantiated display.  
     */
    uint32_t getDspValMax();
    /**
     * @brief Returns a value equivalent to the smallest displayable number for the display. 
     * 
     * The value indicates the smalles displayable number according to the quantity of digits, or ports, the display have as indicated at the object instantiation.
     * 
     * @return The integer number indicating the minimum value that the display might display acording to the quantity of digits of the instantiated display.  
     */
    uint32_t getDspValMin();
    uint16_t getInstanceNbr();
    unsigned long getMaxBlinkRate();
    unsigned long getMinBlinkRate();
    bool isBlank();
    bool isBlinking();
    bool isWaiting();
    bool noBlink();
    bool noWait();
    bool print(String text);
    bool print(const int32_t &value, bool rgtAlgn = false, bool zeroPad = false);
    bool print(const double &value, const unsigned int &decPlaces, bool rgtAlgn = false, bool zeroPad = false);
    void resetBlinkMask();
    void setBlinkMask(const bool* newBlnkMsk);
    bool setBlinkRate(const unsigned long &newOnRate, const unsigned long &newOffRate = 0);
    bool setWaitChar (const char &newChar);
    bool setWaitRate(const unsigned long &newWaitRate);
    bool wait();
    bool wait(const unsigned long &newWaitRate);
    bool write(const uint8_t &segments, const uint8_t &port);
    bool write(const String &character, const uint8_t &port);
};

#endif  //_SevenSegDisplays_H_